# Defines the services (containers) that make up your application.
services:
  # Defines our primary application service, which we'll call 'web'.
  web:
    # Instructs Docker Compose to build the image from the Dockerfile in the current directory ('.').
    build: .
    # Sets the default command to run when the container starts.
    # We use 'nodemon' to automatically restart the server on file changes.
    command: npx nodemon index.js
    # Maps port 3000 on the host machine to port 3000 in the container.
    # This lets us access the app at http://localhost:3000.
    ports:
      - "3000:3000"
    # Mounts the current directory on the host to /usr/src/app in the container.
    # This enables live reloading: changes you make locally are reflected inside the container.
    volumes:
      - .:/usr/src/app
      # Creates an anonymous volume for node_modules. This prevents the node_modules directory
      # inside the container (installed by the Dockerfile) from being overwritten by the empty
      # local node_modules from the volume mount above.
      - /usr/src/app/node_modules
